## Handling Imbalanced Dataset

### Upsampling: Increasing the number of data points in the minority class.
### Downsampling: Reducing the number of data points in the majority class.

In [6]:
import numpy as np
import pandas as pd

np.random.seed(0)

n_samples = 1000
class_zero_ratio = 0.9

n_class_0 = int(n_samples * class_zero_ratio)
n_class_1 = n_samples - n_class_0

In [7]:
n_class_0,n_class_1

(900, 100)

In [8]:
## Create DATAFRAME with imbalanced dataset
class_0 = pd.DataFrame({
    'feature_1': np.random.normal(loc=0, scale=1, size=n_class_0),
    'feature_2': np.random.normal(loc=0, scale=1, size=n_class_0),
    'target': [0] * n_class_0
})

class_1 = pd.DataFrame({
    'feature_1': np.random.normal(loc=2, scale=1, size=n_class_1),
    'feature_2': np.random.normal(loc=2, scale=1, size=n_class_1),
    'target': [1] * n_class_1
})

In [9]:
df = pd.concat([class_0,class_1]).reset_index(drop=True)

In [10]:
df.tail()

     feature_1  feature_2  target
995   1.744529   2.097751       1
996   3.685792   3.401523       1
997   0.351954   2.158434       1
998   2.298714   0.858099       1
999   2.910646   0.689030       1

In [11]:
df['target'].value_counts()

target
0    900
1    100
Name: count, dtype: int64

## Upsampling

In [24]:
df_minortity=df[df['target']==1]
df_majority=df[df['target']==0]

In [15]:
from sklearn.utils import resample

df_minortity_upsampled = resample(df_minortity,replace=True,
         n_samples=len(df_majority),
         random_state=42)

In [17]:
df_minortity_upsampled.shape

(900, 3)

In [18]:
df_minortity_upsampled.head()

     feature_1  feature_2  target
951   1.536978   1.410420       1
992   1.643128   3.315138       1
914   1.237638   3.455808       1
971   1.751581   1.290146       1
960   1.259133   1.791715       1

In [19]:
df_upsampled = pd.concat([df_majority,df_minortity_upsampled])

In [21]:
df_upsampled['target'].value_counts()

target
0    900
1    900
Name: count, dtype: int64

## Downsampling

In [22]:
import numpy as np
import pandas as pd

np.random.seed(0)

n_samples = 1000
class_zero_ratio = 0.9

n_class_0 = int(n_samples * class_zero_ratio)
n_class_1 = n_samples - n_class_0

In [23]:
## Create DATAFRAME with imbalanced dataset
class_0 = pd.DataFrame({
    'feature_1': np.random.normal(loc=0, scale=1, size=n_class_0),
    'feature_2': np.random.normal(loc=0, scale=1, size=n_class_0),
    'target': [0] * n_class_0
})

class_1 = pd.DataFrame({
    'feature_1': np.random.normal(loc=2, scale=1, size=n_class_1),
    'feature_2': np.random.normal(loc=2, scale=1, size=n_class_1),
    'target': [1] * n_class_1
})

In [26]:
df_minority=df[df['target']==1]
df_majority=df[df['target']==0]

In [27]:
from sklearn.utils import resample

df_majority_downsampled = resample(df_majority,replace=False,
         n_samples=len(df_minority),
         random_state=42)

In [28]:
df_majority_downsampled.shape

(100, 3)

In [29]:
df_downsampled = pd.concat([df_minority,df_majority_downsampled])

In [30]:
df_downsampled['target'].value_counts()

target
1    100
0    100
Name: count, dtype: int64