## Label And Ordinal Encoding

### Label Encoding: Assigns a unique integer to each unique category (e.g., 'red'=0, 'green'=1).

In [28]:
from sklearn.preprocessing import LabelEncoder
import pandas as pd

In [29]:
df = pd.DataFrame({"color": ["red", "blue", "green", "red", "blue"]})
df.head()

   color
0    red
1   blue
2  green
3    red
4   blue

In [30]:
lbl_encoder = LabelEncoder()

In [31]:
lbl_encoder.fit_transform(df[['color']])

c:\Users\Inderjeet\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([2, 0, 1, 2, 0])

In [32]:
lbl_encoder.transform(['red'])

array([2])

In [33]:
lbl_encoder.transform(['blue'])

array([0])

In [34]:
lbl_encoder.transform(['green'])

array([1])

## Ordinal Encoding 
### Assigns integers based on a meaningful, pre-defined order (e.g., 'low'=1, 'medium'=2, 'high'=3).

In [35]:
from sklearn.preprocessing import OrdinalEncoder

In [36]:
df = pd.DataFrame({
    'size': ['small', 'medium', 'large', 'medium', 'small', 'large']
})

In [37]:
df

     size
0   small
1  medium
2   large
3  medium
4   small
5   large

In [40]:
encoder = OrdinalEncoder(categories=[['small', 'medium', 'large']])

In [41]:
encoder.fit_transform(df[['size']])

array([[0.],
       [1.],
       [2.],
       [1.],
       [0.],
       [2.]])

In [43]:
encoder.transform([['small']])

c:\Users\Inderjeet\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

array([[0.]])